header: 
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: /world
pose: 
  pose: 
    position: 
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
               0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 
               0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 
               0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 
               0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
               0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
